# Informations de base
spring.application.name=enjeux-strategique
server.port=8802

# Connexion MySQL (même base que les autres)
spring.datasource.url=jdbc:mysql://localhost:3306/systeme?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.show-sql=true

# other microservices
zuul.routes.pip-service.path=/pip/**
zuul.routes.pip-service.serviceId=pip-service
zuul.routes.pip-service.stripPrefix=false

zuul.routes.volet-service.path=/volet/**
zuul.routes.volet-service.serviceId=volet-service
zuul.routes.volet-service.stripPrefix=false

# Configuration des délais de connexion et de socket pour Zuul
zuul.host.connect-timeout-millis=5000
zuul.host.socket-timeout-millis=60000

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# Désactiver Config Server si non utilisé
spring.cloud.config.enabled=false

# Autoriser la redéfinition des beans (utile avec plusieurs @Configuration)
spring.main.allow-bean-definition-overriding=true

# Désactiver Ribbon si on utilise LoadBalancerConfig
ribbon.eureka.enabled=false

# Feign & Hystrix
feign.hystrix.enabled=true
