# Configuration de la base de données (MySQL en local)
spring.datasource.url=jdbc:mysql://localhost:3306/systeme?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.show-sql=true

# Désactivation de Eureka en local
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


spring.cloud.config.enabled=false
spring.main.allow-bean-definition-overriding=true

# Configuration du serveur
spring.application.name=volet-service
server.port=8800

