# application.properties for the Eureka server
#spring.application.name=discovery
#server.port=8761

#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#eureka.instance.hostname=discovery
#eureka.server.wait-time-in-ms-when-sync-empty=0
#eureka.client.service-url.defaultZone=http://discovery:8761/eureka/
#eureka.instance.preferIpAddress=true
# application.properties for the Eureka server (Local Environment)
spring.application.name=discovery
server.port=8761

# Désactive l'enregistrement du serveur auprès de lui-même
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Utilise localhost pour l'exécution locale
eureka.instance.hostname=localhost
eureka.server.wait-time-in-ms-when-sync-empty=0

# URL du service Eureka pour l'environnement local
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Préfère l'IP lors de l'enregistrement
eureka.instance.preferIpAddress=true

